services:
  database:
    image: postgres:16.3-bullseye
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
    container_name: manamano-pg-db
    environment:
      - "POSTGRES_USER=$POSTGRES_USER"
      - "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
      - "POSTGRES_DB=$POSTGRES_DB"
    ports:
      - "$POSTGRES_PORT:5432"
    networks:
      - "main"
    volumes:
      - ./database:/var/lib/postgresql/data

  backend: 
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: "manamano-backend"
    depends_on:
      database:
        condition: service_healthy
    restart: "unless-stopped"
    environment:
      - HOST=$BACKEND_HOST
      - PORT=$BACKEND_PORT
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?schema=public
      - JWT_SECRET=$JWT_SECRET
    command: npm run start:dev
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    networks:
      - "main"
    volumes:
      - "./backend:/usr/src/app/src"
    
volumes:
  database:
  backend:

networks:
  main:
    name: "manamano-net"
