export const bairros = [
  { label: 'Barra da Tijuca', value: '1' },
  { label: 'Barra Olímpica', value: '2' },
  { label: 'Camorim', value: '3' },
  { label: 'Grumari', value: '4' },
  { label: 'Itanhangá', value: '5' },
  { label: 'Joá', value: '6' },
  { label: 'Recreio dos Bandeirantes', value: '7' },
  { label: 'Vargem Grande', value: '8' },
  { label: 'Vargem Pequena', value: '9' },
  { label: 'Centro', value: '10' },
  { label: 'Benfica', value: '11' },
  { label: 'Caju', value: '12' },
  { label: 'Catumbi', value: '13' },
  { label: 'Cidade Nova', value: '14' },
  { label: 'Estácio', value: '15' },
  { label: 'Gamboa', value: '16' },
  { label: 'Glória', value: '17' },
  { label: 'Lapa', value: '18' },
  { label: 'Mangueira', value: '19' },
  { label: 'Rio Comprido', value: '20' },
  { label: 'Santa Teresa', value: '21' },
  { label: 'Santo Cristo', value: '22' },
  { label: 'São Cristóvão', value: '23' },
  { label: 'Saúde', value: '24' },
  { label: 'Vasco da Gama', value: '25' },
  { label: 'Bangu', value: '26' },
  { label: 'Campo dos Afonsos', value: '27' },
  { label: 'Deodoro', value: '28' },
  { label: 'Gericinó', value: '29' },
  { label: 'Jabour', value: '30' },
  { label: 'Jardim Sulacap', value: '31' },
  { label: 'Magalhães Bastos', value: '32' },
  { label: 'Padre Miguel', value: '33' },
  { label: 'Realengo', value: '34' },
  { label: 'Senador Camará', value: '35' },
  { label: 'Vila Kennedy', value: '36' },
  { label: 'Vila Militar', value: '37' },
  { label: 'Alto da Boa Vista', value: '38' },
  { label: 'Andaraí', value: '39' },
  { label: 'Grajaú', value: '40' },
  { label: 'Maracanã', value: '41' },
  { label: 'Praça da Bandeira', value: '42' },
  { label: 'Tijuca', value: '43' },
  { label: 'Vila Isabel', value: '44' },
  { label: 'Bancários', value: '45' },
  { label: 'Cacuia', value: '46' },
  { label: 'Cidade Universitária', value: '47' },
  { label: 'Cocotá', value: '48' },
  { label: 'Freguesia (Ilha do Governador)', value: '49' },
  { label: 'Galeão', value: '50' },
  { label: 'Jardim Carioca', value: '51' },
  { label: 'Jardim Guanabara', value: '52' },
  { label: 'Moneró', value: '53' },
  { label: 'Paquetá', value: '54' },
  { label: 'Pitangueiras', value: '55' },
  { label: 'Portuguesa', value: '56' },
  { label: 'Praia da Bandeira', value: '57' },
  { label: 'Ribeira', value: '58' },
  { label: 'Tauá', value: '59' },
  { label: 'Zumbi', value: '60' },
  { label: 'Jacarepaguá', value: '61' },
  { label: 'Anil', value: '62' },
  { label: 'Cidade de Deus', value: '63' },
  { label: 'Curicica', value: '64' },
  { label: 'Freguesia (Jacarepaguá)', value: '65' },
  { label: 'Gardênia Azul', value: '66' },
  { label: 'Pechincha', value: '67' },
  { label: 'Praça Seca', value: '68' },
  { label: 'Tanque', value: '69' },
  { label: 'Taquara', value: '70' },
  { label: 'Vila Valqueire', value: '71' },
  { label: 'Abolição', value: '72' },
  { label: 'Acari', value: '73' },
  { label: 'Água Santa', value: '74' },
  { label: 'Anchieta', value: '75' },
  { label: 'Barros Filho', value: '76' },
  { label: 'Bento Ribeiro', value: '77' },
  { label: 'Bonsucesso', value: '78' },
  { label: 'Brás de Pina', value: '79' },
  { label: 'Cachambi', value: '80' },
  { label: 'Campinho', value: '81' },
  { label: 'Cascadura', value: '82' },
  { label: 'Cavalcanti', value: '83' },
  { label: 'Coelho Neto', value: '84' },
  { label: 'Colégio', value: '85' },
  { label: 'Complexo do Alemão', value: '86' },
  { label: 'Cordovil', value: '87' },
  { label: 'Costa Barros', value: '88' },
  { label: 'Del Castilho', value: '89' },
  { label: 'Encantado', value: '90' },
  { label: 'Engenheiro Leal', value: '91' },
  { label: 'Engenho da Rainha', value: '92' },
  { label: 'Engenho de Dentro', value: '93' },
  { label: 'Engenho Novo', value: '94' },
  { label: 'Guadalupe', value: '95' },
  { label: 'Higienópolis', value: '96' },
  { label: 'Honório Gurgel', value: '97' },
  { label: 'Inhaúma', value: '98' },
  { label: 'Irajá', value: '99' },
  { label: 'Jacaré', value: '100' },
  { label: 'Jacarezinho', value: '101' },
  { label: 'Jardim América', value: '102' },
  { label: 'Lins de Vasconcelos', value: '103' },
  { label: 'Madureira', value: '104' },
  { label: 'Manguinhos', value: '105' },
  { label: 'Maré', value: '106' },
  { label: 'Marechal Hermes', value: '107' },
  { label: 'Maria da Graça', value: '108' },
  { label: 'Méier', value: '109' },
  { label: 'Olaria', value: '110' },
  { label: 'Oswaldo Cruz', value: '111' },
  { label: 'Parada de Lucas', value: '112' },
  { label: 'Parque Anchieta', value: '113' },
  { label: 'Parque Colúmbia', value: '114' },
  { label: 'Pavuna', value: '115' },
  { label: 'Penha', value: '116' },
  { label: 'Penha Circular', value: '117' },
  { label: 'Piedade', value: '118' },
  { label: 'Pilares', value: '119' },
  { label: 'Quintino Bocaiuva', value: '120' },
  { label: 'Ramos', value: '121' },
  { label: 'Riachuelo', value: '122' },
  { label: 'Ricardo de Albuquerque', value: '123' },
  { label: 'Rocha', value: '124' },
  { label: 'Rocha Miranda', value: '125' },
  { label: 'Sampaio', value: '126' },
  { label: 'São Francisco Xavier', value: '127' },
  { label: 'Todos os Santos', value: '128' },
  { label: 'Tomás Coelho', value: '129' },
  { label: 'Turiaçu', value: '130' },
  { label: 'Vaz Lobo', value: '131' },
  { label: 'Vicente de Carvalho', value: '132' },
  { label: 'Vigário Geral', value: '133' },
  { label: 'Vila da Penha', value: '134' },
  { label: 'Vila Kosmos', value: '135' },
  { label: 'Vista Alegre', value: '136' },
  { label: 'Barra de Guaratiba', value: '137' },
  { label: 'Campo Grande', value: '138' },
  { label: 'Cosmos', value: '139' },
  { label: 'Guaratiba', value: '140' },
  { label: 'Ilha de Guaratiba', value: '141' },
  { label: 'Inhoaíba', value: '142' },
  { label: 'Paciência', value: '143' },
  { label: 'Pedra de Guaratiba', value: '144' },
  { label: 'Santa Cruz', value: '145' },
  { label: 'Santíssimo', value: '146' },
  { label: 'Senador Vasconcelos', value: '147' },
  { label: 'Sepetiba', value: '148' },
  { label: 'Botafogo', value: '149' },
  { label: 'Catete', value: '150' },
  { label: 'Copacabana', value: '151' },
  { label: 'Cosme Velho', value: '152' },
  { label: 'Flamengo', value: '153' },
  { label: 'Gávea', value: '154' },
  { label: 'Humaitá', value: '155' },
  { label: 'Ipanema', value: '156' },
  { label: 'Jardim Botânico', value: '157' },
  { label: 'Lagoa', value: '158' },
  { label: 'Laranjeiras', value: '159' },
  { label: 'Leblon', value: '160' },
  { label: 'Leme', value: '161' },
  { label: 'Rocinha', value: '162' },
  { label: 'São Conrado', value: '163' },
  { label: 'Urca', value: '164' },
  { label: 'Vidigal', value: '165' },
];
export const etnias = [
  { label: 'Amarela', value: '1' },
  { label: 'Branca', value: '2' },
  { label: 'Indígena', value: '3' },
  { label: 'Parda', value: '4' },
  { label: 'Preta', value: '5' },
];
export const especialidades = [
  { label: 'Confeitaria', value: '1' },
  { label: 'Manicure e Pedicure', value: '2' },
  { label: 'Costura e Moda', value: '3' },
  { label: 'Cabelereira', value: '4' },
  { label: 'Maquiagem e Estética', value: '5' },
  { label: 'Culinária Artesanal', value: '6' },
  { label: 'Artesanato', value: '7' },
  { label: 'Vendas de Cosméticos', value: '8' },
  { label: 'Brechó e Moda Sustentável', value: '9' },
  { label: 'Fotografia', value: '10' },
  { label: 'Aulas de Dança', value: '11' },
  { label: 'Personal Trainer', value: '12' },
  { label: 'Decoração de Festas', value: '13' },
  { label: 'Cuidadora de Idosos', value: '14' },
  { label: 'Cuidado Infantil (Babá)', value: '15' },
  { label: 'Produção de Bijuterias', value: '16' },
  { label: 'Marcenaria', value: '17' },
  { label: 'Cestas de Café da Manhã', value: '18' },
  { label: 'Produção de Velas Artesanais', value: '19' },
  { label: 'Bolos e Doces Decorados', value: '20' },
  { label: 'Marmitas Saudáveis', value: '21' },
  { label: 'Aulas de Reforço Escolar', value: '22' },
  { label: 'Produção de Sabonetes Artesanais', value: '23' },
  { label: 'Confecção de Lembrancinhas', value: '24' },
  { label: 'Costura Criativa', value: '25' },
  { label: 'Design Gráfico', value: '26' },
  { label: 'Fotografia de Eventos', value: '27' },
  { label: 'Serviços de Marketing Digital', value: '28' },
  { label: 'Venda de Produtos Naturais', value: '29' },
  { label: 'Aluguel de Trajes para Festas', value: '30' },
];
